name = "SOD321Project"
uuid = "2cf540f4-bdb5-11e8-2ee5-8946e585a5a6"
authors = ["Gilles Bareilles <gilles.bareilles@gmail.com>"]
version = "0.1.0"

[deps]
GLPK = "60bf3e95-4087-53dc-ae20-288a0d20c6a6"
GR = "28b8d3ca-fb5f-59d9-8090-bfdbd6d07a71"
JuMP = "4076af6c-e467-56ae-b986-b466b2749572"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
